// Code généré automatiquement. Ne pas modifier.
namespace myImages {

    helpers._registerFactory("image", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "image1":
            case "Moob_1":return img`
................................
................................
................................
................................
...........2........2...........
...........2........2...........
...........2........2...........
..........22........22..........
..........22........22..........
...........2..fff...2...........
...........22fffff222...........
.............f2f2f..............
.............fffff..............
..........fffffffffff...........
.........ffffff2ffffff..........
........fffffff2fffffff.........
........ffffff222ffffff.........
........fff.ff2f2ff.fff.........
........fff.f22f22f.fff.........
........fff.ff222ff.fff.........
........fff..f222f..fff.........
.........f...ff2ff...f..........
.............fffff..............
.............fffff..............
................................
................................
................................
................................
................................
................................
................................
................................
`;
            case "image2":
            case "Hero epee haute droite":return img`
...7..ee....7.......
....7feef..77.......
....feeeef.7........
....effffee.........
....eddddde.........
.....dfddd..........
.....dfdddf....fff..
.....dddff....ffdf..
.....ddddd...ffddf..
...ccf2f2fccffddff..
...cf1fff1fcfddff...
...d2ff9ff2dfdff....
...dd2fff2ddfff.....
.....f1f1f..........
.....66666..........
.....66.66..........
.....66.66..........
...ffff.ffff........
....................
....................
`;
            case "image6":
            case "Hero epée haute drotie":return img`
...7..ee....7.......
....7feef..77.......
....feeeef.7........
....effffee.........
....eddddde.........
.....dfddd..........
.....dfdddf....fff..
.....dddff....ffdf..
.....ddddd...ffddf..
...ccf2f2fccffddff..
...cf1fff1fcfddff...
...d2ff9ff2dfdff....
...dd2fff2ddfff.....
.....f1f1f..........
.....66666..........
.....66.66..........
.....66.66..........
...ffff.ffff........
....................
....................
`;
            case "image3":
            case "Hero epee milieu droite":return img`
....................
...7..ee....7.......
....7feef..77.......
....feeeef.7........
....effffee.........
....eddddde.........
.....dfddd..........
.....dfdddf.........
.....dddff..........
.....ddddd..........
...ccf2f2fcc........
...cf1fff1fcffffff..
...d2ff9ff2dfdddddf.
...dd2fff2ddffffff..
.....f1f1f..........
.....66666..........
.....66.66..........
.....66.66..........
...ffff.ffff........
....................
`;
            case "image4":
            case "hero epee droite basse":return img`
...7..ee....7.......
....7feef..77.......
....feeeef.7........
....effffee.........
....eddddde.........
.....dfddd..........
.....dfdddf.........
.....dddff..........
.....ddddd..........
...ccf2f2fcc........
...cf1fff1fc........
...d2ff9ff2dfff.....
...dd2fff2ddfdff....
.....f1f1f..fddff...
.....66666..ffddff..
.....66.66...ffddf..
.....66.66....ffdf..
...ffff.ffff...fff..
....................
....................
`;
        }
        return null;
    })

    helpers._registerFactory("animation", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

    helpers._registerFactory("song", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

    helpers._registerFactory("json", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

}
// Code généré automatiquement. Ne pas modifier.
